apiVersion: v1
kind: Secret
metadata:
  name: pad-secrets
  namespace: pad
  labels:
    app: pad
type: Opaque
data:
  # Generate with: echo -n "your-secret-key-here" | base64
  # Example: echo -n "super-secret-key-change-this-in-production" | base64
  BETTER_AUTH_SECRET: c3VwZXItc2VjcmV0LWtleS1jaGFuZ2UtdGhpcy1pbi1wcm9kdWN0aW9u
  
  # Optional: Add other secrets as needed
  # GOOGLE_CLIENT_SECRET: ""
  # GITHUB_CLIENT_SECRET: ""
---
# Template for creating your own secret with proper values
# Run these commands to create the secret properly:
#
# kubectl create secret generic pad-secrets \
#   --from-literal=BETTER_AUTH_SECRET='your-actual-secret-here' \
#   --namespace=pad
#
# Or base64 encode your secrets:
# echo -n "your-actual-secret" | base64