import type {Metadata} from "next";
import {Inter, JetBrains_Mono, Newsreader, Noto_Sans} from "next/font/google";
import "./globals.css";
import {cn} from "@/lib/utils";
import {ReactNode, Suspense} from "react";
import {ThemeProvider} from "next-themes";
import {WebsiteWrapper} from "@/components/website-wrapper";
import {getSiteConfig} from "@/lib/data";
import {Loading} from "@/components/loading";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const inter = Inter ({
	subsets: ['latin'],
	weight: ['300', '400', '500', '600', '700'],
	variable: '--font-inter',
})

const jetbrainsMono = JetBrains_Mono ({
	subsets: ['latin'],
	weight: ['400', '500', '600'],
	variable: '--font-jetbrains-mono',
})

const newsreader = Newsreader ({
	subsets: ['latin'],
	weight: ['400', '500', '700', '800'],
	variable: '--font-newsreader',
})

const notoSans = Noto_Sans ({
	subsets: ['latin'],
	weight: ['400', '500', '700', '900'],
	variable: '--font-noto-sans',
})

export default function RootLayout ({children}: { children: ReactNode }) {
	return (
		<html lang="en">
			<body
				className={cn (
					inter.variable,
					jetbrainsMono.variable,
					newsreader.variable,
					notoSans.variable,
					"antialiased",
				)}
			>
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					disableTransitionOnChange
				>
					<Suspense fallback={<Loading />}>
						<WebsiteWrapper promise={getSiteConfig()}>
							{children}
						</WebsiteWrapper>
					</Suspense>
				</ThemeProvider>
			</body>
		</html>
	);
}
